-- 1. Drop existing table to recreate with new structure (Clean slate for this feature)
drop table if exists public.app_config;

-- 2. Create the Config Table with Environment support
create table public.app_config (
  id bigint generated by default as identity primary key,
  key text not null,
  value text not null,
  description text,
  environment text not null default 'production', -- 'production' or 'beta'
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Constraint: A key can exist once per environment
  constraint section_key_env_unique unique (key, environment)
);

-- 3. Enable Security
alter table public.app_config enable row level security;

create policy "Allow public read access"
  on public.app_config
  for select
  using (true);

create policy "Allow internal update access"
  on public.app_config
  for all
  using (auth.role() = 'service_role');

-- 4. Insert Keys (Strategy: Version 2 -> Beta, Version 1 -> Production)
insert into public.app_config (key, value, environment, description)
values
  -- PRODUCTION KEYS (Version 1 - Safe/Stable?)
  ('groq_api_key', '<INSIRA_CHAVE_AQUI_PROD>', 'production', 'Chave de Produção (Versão 1)'),
  ('groq_model', 'llama-3.3-70b-versatile', 'production', 'Modelo Produção'),

  -- BETA KEYS (Version 2 - Bleeding Edge/Admin)
  ('groq_api_key', '<INSIRA_CHAVE_AQUI_BETA>', 'beta', 'Chave Beta/Admin (Versão 2)'),
  ('groq_model', 'llama-3.3-70b-versatile', 'beta', 'Modelo Beta');
