const db = require('../db');

async function checkStatus() {
    let conn;
    try {
        conn = await db.getConnection();
        const books = await conn.execute(
            `SELECT count(*) FROM user_tables WHERE table_name = 'TB_DOC_BOOKS'`
        );
        const nodes = await conn.execute(
            `SELECT count(*) FROM user_tables WHERE table_name = 'TB_DOC_NODES'`
        );
        return {
            booksTable: books.rows[0][0] > 0,
            nodesTable: nodes.rows[0][0] > 0,
            ready: (books.rows[0][0] > 0 && nodes.rows[0][0] > 0)
        };
    } catch (err) {
        console.error("Check Status Error:", err);
        return { ready: false, error: err.message };
    } finally {
        if (conn) try { await conn.close(); } catch (e) { }
    }
}

async function initializeDatabase() {
    let conn;
    const logs = [];
    function log(msg) {
        console.log("[DocsInit]", msg);
        logs.push(msg);
    }

    try {
        conn = await db.getConnection();

        // 1. TB_DOC_BOOKS
        log("Checking TB_DOC_BOOKS...");
        try {
            await conn.execute(`SELECT 1 FROM TB_DOC_BOOKS FETCH NEXT 1 ROWS ONLY`);
            log("TB_DOC_BOOKS already exists.");
        } catch (e) {
            if (e.errorNum === 942) {
                log("Creating TB_DOC_BOOKS...");
                await conn.execute(`
                    CREATE TABLE TB_DOC_BOOKS (
                        ID_BOOK NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                        NM_TITLE VARCHAR2(255) NOT NULL,
                        DS_DESCRIPTION VARCHAR2(1000),
                        DT_CREATED DATE DEFAULT SYSDATE,
                        CD_OWNER VARCHAR2(100)
                    )
                `);
                log("TB_DOC_BOOKS created.");
            } else {
                throw e;
            }
        }

        // 2. TB_DOC_NODES
        log("Checking TB_DOC_NODES...");
        try {
            await conn.execute(`SELECT 1 FROM TB_DOC_NODES FETCH NEXT 1 ROWS ONLY`);
            log("TB_DOC_NODES already exists.");
        } catch (e) {
            if (e.errorNum === 942) {
                log("Creating TB_DOC_NODES...");
                await conn.execute(`
                    CREATE TABLE TB_DOC_NODES (
                        ID_NODE NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                        ID_BOOK NUMBER NOT NULL,
                        ID_PARENT_NODE NUMBER,
                        NM_TITLE VARCHAR2(255) NOT NULL,
                        TP_NODE VARCHAR2(50) DEFAULT 'PAGE',
                        CL_CONTENT CLOB,
                        NU_ORDER NUMBER DEFAULT 0,
                        DT_UPDATED DATE DEFAULT SYSDATE,
                        CONSTRAINT FK_DOC_BOOK FOREIGN KEY (ID_BOOK) REFERENCES TB_DOC_BOOKS(ID_BOOK) ON DELETE CASCADE,
                        CONSTRAINT FK_DOC_PARENT FOREIGN KEY (ID_PARENT_NODE) REFERENCES TB_DOC_NODES(ID_NODE) ON DELETE CASCADE
                    )
                `);
                log("TB_DOC_NODES created.");
            } else {
                throw e;
            }
        }

        log("Database initialization completed successfully.");
        return { success: true, logs };

    } catch (err) {
        log("Error initializing database: " + err.message);
        return { success: false, logs, error: err.message };
    } finally {
        if (conn) try { await conn.close(); } catch (e) { }
    }
}

module.exports = {
    checkStatus,
    initializeDatabase
};
